name: Sanity Tests

on:
 workflow_dispatch:
 
jobs:
  setup:
    runs-on: ubuntu-latest
    
    outputs:
      qaboot_hostname: ${{ steps.run_qaboot.outputs.qaboot_hostname }}
      
    permissions:
      contents: read
      
    steps:
    - name: Build + Launch GHES with qaboot
      id: run_qaboot
      env:
        QABOOT_USER: ${{ env.USER }}
        # QABOOT_GITHUB_TOKEN: ${{ secrets.QABOOT_GITHUB_TOKEN }}
        # QABOOT_AWS_ACCESS_KEY_ID: ${{ secrets.QABOOT_AWS_ACCESS_KEY_ID }}
        # QABOOT_AWS_SECRET_ACCESS_KEY: ${{ secrets.QABOOT_AWS_SECRET_ACCESS_KEY }}
        # QABOOT_ROUTE53_ACCESS_KEY_ID: ${{ secrets.QABOOT_AWS_ACCESS_KEY_ID }}
        # QABOOT_ROUTE53_SECRET_ACCESS_KEY: ${{ secrets.QABOOT_AWS_SECRET_ACCESS_KEY }} 
      run: |
        # gem install bundler
        # bundle install --local --jobs 8 --retry 3
        # eval `ssh-agent -s`
        # ssh-add ~/.ssh/id_rsa
        # bundle exec qaboot $GHES_VERSION --platform $GHES_PLATFORM --region $GHES_REGION --do-setup --generate-ssl | tee output.log
        # QABOOT_HOSTNAME=$(awk -F'http[s]?://' '{print $2}' output.log | awk '{print $1}' | xargs)
        QABOOT_HOSTNAME=fushigi.com
        echo "adding qaboot_hostname: $QABOOT_HOSTNAME to job outputs"
        echo "qaboot_hostname=$QABOOT_HOSTNAME" >> $GITHUB_OUTPUT
        echo "printing GITHUB_ENV!"
        cat $GITHUB_ENV
        
  run-tests:
    needs: [setup]
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
      env:
        QABOOT_HOSTNAME: ${{ needs.setup.outputs.qaboot_hostname }}
        BAR: ${{ env.FOOBAR }}
    env:
      QABOOT_HOSTNAME: ${{ needs.setup.outputs.qaboot_hostname }}
      FOOBAR: "yes it is foobar"
      
    steps:
    - name: Print ENV
      run: env
        
